Document: canaima-instalador
Title: Debian canaima-instalador Manual
Author: <insert document author here>
Abstract: This manual describes what canaima-instalador is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/canaima-instalador/canaima-instalador.sgml.gz

Format: postscript
Files: /usr/share/doc/canaima-instalador/canaima-instalador.ps.gz

Format: text
Files: /usr/share/doc/canaima-instalador/canaima-instalador.text.gz

Format: HTML
Index: /usr/share/doc/canaima-instalador/html/index.html
Files: /usr/share/doc/canaima-instalador/html/*.html
