#!/bin/sh -e
#
# ==============================================================================
# PAQUETE: canaima-instalador
# ARCHIVO: postrm
# DESCRIPCIÓN: Revierte los cambios hechos por el paquete en los scripts del
#              mantenedor, de forma tal de asegurarse que el sistema quede
#              como estaba antes de su instalación.
# COPYRIGHT:
#  (C) 2011 William Abrahan Cabrera Reyes <william@linux.es>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

ERROR() {
	printf "\033[1;31m${1}\033[0m\n"
}

ADVERTENCIA() {
	printf "\033[1;33m${1}\033[0m\n"
}

EXITO() {
	printf "\033[1;32m${1}\033[0m\n"
}

case ${1} in

	purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		# Para cada usuario en /home/ ...
		for USERNAME in $( ls -1 "/home/" ); do
			# Y en caso de que el usuario sea un usuario activo (existente en /etc/shadow) ...
			if [ $( grep -c "${USERNAME}:.*:.*:.*:.*:.*:::" /etc/shadow ) -eq 1 ] \
			&& [ $( grep -c "${USERNAME}:.*:.*:.*:.*:.*:/bin/.*sh" /etc/passwd ) -eq 1 ] \
			&& [ -d "/home/${USERNAME}/.config" ] && [ -d "/home/${USERNAME}/Escritorio" ]; then

				ADVERTENCIA 'Removiendo lanzador de escritorio para el usuario "'${USERNAME}'"'

				# Removemos el lanzador
				rm -rf /home/${USERNAME}/Escritorio/canaima-instalador.desktop
			fi
		done
	;;

	*)

		ERROR "postrm no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac

#DEBHELPER#

exit 0
