#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-instalador
# ARCHIVO: postinst
# DESCRIPCIÓN: Configura el sistema despues la instalación del paquete.
# COPYRIGHT:
#  (C) 2011 William Abrahan Cabrera Reyes <william@linux.es>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="canaima-instalador"

# Color Verde
VERDE="\e[1;32m"
# Color Rojo
ROJO="\e[1;31m"
# Color Amarillo
AMARILLO="\e[1;33m"
# Negrita
BOLD="\e[1m"
# Caracter de fin de línea
FIN="\e[0m"

function ERROR() {
echo -e ${ROJO}${1}${FIN}
}

function ADVERTENCIA() {
echo -e ${AMARILLO}${1}${FIN}
}

function EXITO() {
echo -e ${VERDE}${1}${FIN}
}

case ${1} in

	configure)

	# Para cada usuario en /home/ ...
	for usuario in /home/*? ; do

		# Obteniendo sólo el nombre del usuario
		usuario_min=$(basename ${usuario})

		# Y en caso de que el usuario sea un usuario activo (existente en /etc/shadow) ...
		case  $( grep "${usuario_min}:.*:.*:.*:.*:.*:::" /etc/shadow ) in

			'')
			# No hace nada si no se encuentra en /etc/shadow
			;;

			*)
				ADVERTENCIA 'Instalando Canaima Instalador Vivo para el usuario "'$usuario_min'"'
				# Copiamos el lanzador de escritorio al escritorio de cada usuario
				cp /etc/skel/Escritorio/canaima-instalador.desktop /home/${usuario_min}/Escritorio/
				# con permisos apropiados
				chown ${usuario_min}:${usuario_min} /home/${usuario_min}/Escritorio/canaima-instalador.desktop
			;;
		esac
	done
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)

		echo "postinst no reconoce el argumento '"${1}"'" >&2
		exit 1

	;;

esac

#DEBHELPER#

exit 0
