#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-instalador
# ARCHIVO: postrm
# DESCRIPCIÓN: Revierte los cambios hechos por el paquete en los scripts del
#              mantenedor, de forma tal de asegurarse que el sistema quede
#              como estaba antes de su instalación.
# COPYRIGHT:
#  (C) 2011 William Abrahan Cabrera Reyes <william@linux.es>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

# Color Verde
VERDE="\e[1;32m"
# Color Rojo
ROJO="\e[1;31m"
# Color Amarillo
AMARILLO="\e[1;33m"
# Negrita
BOLD="\e[1m"
# Caracter de fin de línea
FIN="\e[0m"

PKG="canaima-instalador"

function remove_divert {
    if [ -f /etc/gdm3/Init/Default ];
    then
        #dpkg-divert --package ${PKG} --rename --remove /etc/gdm3/Init/Default
        ADVERTENCIA "borrando linea"
        sed  -i  ':a;N;$!ba;s#/usr/bin/canaima-oem\n\n##g' /etc/gdm3/Init/Default
    fi
}

function ERROR() {
echo -e ${ROJO}${1}${FIN}
}

function ADVERTENCIA() {
echo -e ${AMARILLO}${1}${FIN}
}

function EXITO() {
echo -e ${VERDE}${1}${FIN}
}


case ${1} in

	purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	# Para cada usuario en /home/ ...
	for usuario in /home/*? ; do
    	remove_divert

		# Obteniendo sólo el nombre del usuario
		usuario_min=$(basename ${usuario})

		# Y en caso de que el usuario sea un usuario activo (existente en /etc/shadow) ...
		case  $( grep "${usuario_min}:.*:.*:.*:.*:.*:::" /etc/shadow ) in

			'')
			# No hace nada si no se encuentra en /etc/shadow
			;;

			*)
				ADVERTENCIA 'Removiendo Instalador para el usuario "'$usuario_min'"'
				[ -e /home/${usuario_min}/Escritorio/canaima-instalador.desktop ] && rm /home/${usuario_min}/Escritorio/canaima-instalador.desktop
			;;
		esac
	done
	;;

	*)

		echo "postrm no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac

#DEBHELPER#

exit 0
