#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-instalador
# ARCHIVO: preinst
# DESCRIPCIÓN: Configura el sistema antes de la instalación del paquete.
# COPYRIGHT:
#  (C) 2011 William Abrahan Cabrera Reyes <william@linux.es>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="canaima-instalador"

function remove_divert {
    if [ -f /etc/gdm3/Init/Default ];
    then
        #dpkg-divert --package ${PKG} --rename --remove /etc/gdm3/Init/Default
        sed  -i  ':a;N;$!ba;s#/usr/bin/canaima-oem\n\nexit 0#exit 0#g' /etc/gdm3/Init/Default
    fi
}
case ${1} in

	install|upgrade)
        #dpkg-divert --package ${PKG} --divert /etc/gdm3/Init/Default.real --rename /etc/gdm3/Init/Default
        sed  -i  's#exit 0#/usr/bin/canaima-oem\n\nexit 0#g' /etc/gdm3/Init/Default
	# Aquí va lo que el paquete debe configurar/crear/borrar antes de
	# instalarse. Lenguaje a usar: BASH.

	;;

    abort-upgrade)
        remove_divert
    # Aquí va lo que el paquete debe configurar/crear/borrar si se
    # aborta el proceso de actualizar un paquete a una versión superior.
	# Lenguaje a usar: BASH.

        ;;

        *)
                echo "preinst no reconoce el argumento '"${1}"'" >&2
                exit 1
        ;;

esac

#DEBHELPER#

exit 0
